const SUPABASE_URL='https://tuqjkuqvyqqswcsgvjrh.supabase.co';
const SUPABASE_KEY='sb_publishable_8LBj67R2IW6jTh5oJY2hPA_e-vuOooF';
const PAYMENT_FN=SUPABASE_URL+'/functions/v1/payment';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let editingId=null,currentOrders=[];
const fa=n=>Number(n||0).toLocaleString('fa-IR')+' تومان';
async function boot(){const {data:{session}}=await db.auth.getSession();if(session)await enter(session);else document.getElementById('login').classList.remove('hidden');db.auth.onAuthStateChange(async(_e,s)=>{if(s)await enter(s)})}
async function login(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,msg=document.getElementById('loginMsg');msg.textContent='';if(!email||!password){msg.textContent='ایمیل و رمز عبور را وارد کنید.';return}const {data,error}=await db.auth.signInWithPassword({email,password});if(error){msg.textContent='ورود ناموفق بود.';return}await enter(data.session)}
async function enter(session){const {data:admin}=await db.from('shop_admins').select('user_id').eq('user_id',session.user.id).maybeSingle();if(!admin){await db.auth.signOut();document.getElementById('loginMsg').textContent='این حساب دسترسی مدیر ندارد.';return}document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('adminEmail').textContent=session.user.email||'';await loadAll()}
async function logout(){await db.auth.signOut();location.reload()}
function showTab(id,btn){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('aside nav button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');document.getElementById('pageTitle').textContent=id==='dashboard'?'داشبورد':id==='products'?'محصولات':'سفارش‌ها';if(id==='dashboard')loadDashboard();if(id==='products')loadProducts();if(id==='orders')loadOrders()}
function showTabById(id){const btn=[...document.querySelectorAll('aside nav button')].find(b=>b.getAttribute('onclick')?.includes("'"+id+"'"));showTab(id,btn)}
async function loadAll(){await Promise.all([loadDashboard(),loadProducts(),loadOrders()])}
async function loadDashboard(){const a=await db.from('orders').select('*').order('created_at',{ascending:false}),b=await db.from('products').select('id,active');const orders=a.data||[],products=b.data||[],paid=orders.filter(x=>x.status==='paid');document.getElementById('revenue').textContent=fa(paid.reduce((s,x)=>s+Number(x.total_toman||0),0));document.getElementById('ordersCount').textContent=orders.length.toLocaleString('fa-IR');document.getElementById('productsCount').textContent=products.filter(x=>x.active).length.toLocaleString('fa-IR');document.getElementById('pendingCount').textContent=orders.filter(x=>x.status==='pending').length.toLocaleString('fa-IR');document.getElementById('recentOrders').innerHTML=orderTable(orders.slice(0,8))}
function status(s){return {pending:'در انتظار پرداخت',paid:'پرداخت‌شده',failed:'ردشده',cancelled:'لغوشده'}[s]||s}
function orderTable(rows){if(!rows.length)return '<p>هنوز سفارشی ثبت نشده است.</p>';return '<table class="table"><tr><th>شماره</th><th>مشتری</th><th>مبلغ</th><th>وضعیت</th><th>تاریخ</th><th>عملیات</th></tr>'+rows.map(x=>'<tr><td>#'+Number(x.order_number).toLocaleString('fa-IR')+'</td><td>'+safe(x.customer_name||'-')+'</td><td>'+fa(x.total_toman)+'</td><td><span class="badge '+(x.status==='paid'?'paid':x.status==='failed'?'failed':'')+'">'+status(x.status)+'</span></td><td>'+new Date(x.created_at).toLocaleDateString('fa-IR')+'</td><td class="actions"><button class="details" onclick="openOrder('+Number(x.order_number)+')">جزئیات</button>'+(x.status==='pending'?'<button class="edit" onclick="approveOrder('+Number(x.order_number)+')">✓ تأیید</button><button class="delete" onclick="rejectOrder('+Number(x.order_number)+')">× رد</button>':x.status==='paid'?'<span>🔓 دانلود فعال</span>':'—')+'</td></tr>').join('')+'</table>'}
async function loadOrders(){const {data,error}=await db.from('orders').select('*').order('created_at',{ascending:false});currentOrders=data||[];renderOrders();if(error)document.getElementById('ordersTable').innerHTML='<p>خطا در دریافت سفارش‌ها.</p>'}
function renderOrders(){let rows=[...currentOrders],q=(document.getElementById('orderSearch')?.value||'').trim().toLowerCase(),f=document.getElementById('orderFilter')?.value||'all';if(f!=='all')rows=rows.filter(x=>x.status===f);if(q)rows=rows.filter(x=>[x.order_number,x.customer_name,x.customer_email,x.customer_mobile].join(' ').toLowerCase().includes(q));document.getElementById('ordersTable').innerHTML=orderTable(rows)}
async function openOrder(n){const order=currentOrders.find(x=>Number(x.order_number)===Number(n));if(!order)return;document.getElementById('orderDetails').innerHTML='<p>در حال دریافت جزئیات...</p>';document.getElementById('orderModal').classList.remove('hidden');const {data:items,error}=await db.from('order_items').select('product_name,unit_price_toman,product_id').eq('order_id',order.id);if(error){document.getElementById('orderDetails').innerHTML='<p>خطا در دریافت اقلام سفارش.</p>';return}const date=new Date(order.created_at).toLocaleString('fa-IR');document.getElementById('orderDetails').innerHTML='<div class="order-title"><h2>سفارش #'+Number(order.order_number).toLocaleString('fa-IR')+'</h2><span class="badge '+(order.status==='paid'?'paid':order.status==='failed'?'failed':'')+'">'+status(order.status)+'</span></div><div class="detail-grid"><div class="detail-box"><small>نام مشتری</small><strong>'+safe(order.customer_name||'-')+'</strong></div><div class="detail-box"><small>موبایل</small><strong>'+safe(order.customer_mobile||'-')+'</strong></div><div class="detail-box"><small>ایمیل</small><strong>'+safe(order.customer_email||'-')+'</strong></div><div class="detail-box"><small>روش پرداخت</small><strong>کارت‌به‌کارت</strong></div><div class="detail-box"><small>زمان ثبت</small><strong>'+date+'</strong></div><div class="detail-box"><small>مبلغ کل</small><strong>'+fa(order.total_toman)+'</strong></div></div><div class="items"><h3>🛍️ اقلام سفارش</h3>'+((items||[]).map(i=>'<div class="item"><span>'+safe(i.product_name)+'</span><strong>'+fa(i.unit_price_toman)+'</strong></div>').join('')||'<p>بدون قلم</p>')+'</div>'+(order.status==='pending'?'<div class="order-actions"><button class="approve" onclick="approveOrder('+Number(order.order_number)+');closeOrder()">✓ تأیید پرداخت و فعال‌سازی دانلود</button><button class="reject" onclick="rejectOrder('+Number(order.order_number)+');closeOrder()">× رد سفارش</button></div>':order.status==='paid'?'<div class="order-actions"><button class="approve" disabled>🔓 دانلود فعال است</button></div>':'')}
function closeOrder(){document.getElementById('orderModal').classList.add('hidden')}
async function callPayment(action,orderNumber){const {data:{session}}=await db.auth.getSession();if(!session)throw new Error('جلسه مدیر منقضی شده است.');const res=await fetch(PAYMENT_FN,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token,apikey:SUPABASE_KEY},body:JSON.stringify({action,order_number:orderNumber})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||'عملیات ناموفق بود.');return data}
async function approveOrder(n){if(!confirm('پرداخت سفارش #'+Number(n).toLocaleString('fa-IR')+' تأیید شود؟'))return;try{await callPayment('approve',n);alert('پرداخت تأیید شد و دانلود فعال شد.');await loadAll()}catch(e){alert(e.message)}}
async function rejectOrder(n){if(!confirm('سفارش #'+Number(n).toLocaleString('fa-IR')+' رد شود؟'))return;try{await callPayment('reject',n);alert('سفارش رد شد.');await loadAll()}catch(e){alert(e.message)}}
async function loadProducts(){const {data,error}=await db.from('products').select('*').order('id');if(error){document.getElementById('productsTable').textContent='خطا در دریافت محصولات.';return}document.getElementById('productsTable').innerHTML='<table class="table"><tr><th>نام</th><th>دسته</th><th>قیمت</th><th>وضعیت</th><th>عملیات</th></tr>'+(data||[]).map(p=>'<tr><td>'+safe(p.name)+'</td><td>'+safe(p.category)+'</td><td>'+fa(p.price_toman)+'</td><td>'+(p.active?'فعال':'غیرفعال')+'</td><td class="actions"><button class="edit" onclick="openProductById('+p.id+')">ویرایش</button><button class="delete" onclick="removeProduct('+p.id+')">حذف</button></td></tr>').join('')+'</table>'}
async function openProductById(id){const {data}=await db.from('products').select('*').eq('id',id).single();if(data)openProduct(data)}
function openProduct(p=null){editingId=p?.id||null;document.getElementById('modalTitle').textContent=p?'ویرایش محصول':'محصول جدید';document.getElementById('pName').value=p?.name||'';document.getElementById('pCategory').value=p?.category||'study';document.getElementById('pPrice').value=p?.price_toman??'';document.getElementById('pDesc').value=p?.description||'';document.getElementById('pFile').value=p?.file_path||'';document.getElementById('pActive').checked=p?.active??true;document.getElementById('productMsg').textContent='';document.getElementById('productModal').classList.remove('hidden')}
function closeProduct(){document.getElementById('productModal').classList.add('hidden')}
async function saveProduct(){const msg=document.getElementById('productMsg'),payload={name:document.getElementById('pName').value.trim(),category:document.getElementById('pCategory').value,price_toman:Number(document.getElementById('pPrice').value),description:document.getElementById('pDesc').value.trim(),file_path:document.getElementById('pFile').value.trim(),active:document.getElementById('pActive').checked};if(!payload.name||payload.price_toman<0){msg.textContent='نام و قیمت معتبر وارد کنید.';return}const res=editingId?await db.from('products').update(payload).eq('id',editingId):await db.from('products').insert(payload);if(res.error){msg.textContent='ذخیره انجام نشد.';return}closeProduct();await loadAll()}
async function removeProduct(id){if(!confirm('این محصول حذف شود؟'))return;const {error}=await db.from('products').delete().eq('id',id);if(error)alert('حذف انجام نشد.');else await loadAll()}
function safe(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
boot();