const API='https://tuqjkuqvyqqswcsgvjrh.supabase.co/functions/v1/payment';const API_KEY='sb_publishable_8LBj67R2IW6jTh5oJY2hPA_e-vuOooF';
const CARD_NUMBER='شماره کارت فروشنده را اینجا وارد کنید';
const products=[{id:1,name:'پک جزوه و برنامه‌ریزی دانش‌آموزی',cat:'study',price:79000,icon:'📚',desc:'فایل‌های PDF آماده برای برنامه‌ریزی و مطالعه.'},{id:2,name:'پک قالب پست اینستاگرام',cat:'design',price:129000,icon:'🎨',desc:'قالب‌های قابل ویرایش برای تولید محتوای سریع.'},{id:3,name:'فایل مدیریت دخل‌وخرج',cat:'business',price:99000,icon:'📊',desc:'فایل آماده برای مدیریت ساده درآمد و هزینه.'},{id:4,name:'پک پرامپت‌های هوش مصنوعی',cat:'tools',price:69000,icon:'🤖',desc:'پرامپت‌های آماده برای تولید محتوا و ایده‌پردازی.'},{id:5,name:'قالب رزومه حرفه‌ای',cat:'design',price:89000,icon:'📄',desc:'قالب رزومه فارسی با طراحی تمیز و قابل ویرایش.'},{id:6,name:'پک چک‌لیست مطالعه',cat:'study',price:49000,icon:'✅',desc:'چک‌لیست‌های چاپی و دیجیتال برای مدیریت درس‌ها.'}];
let selected='all',cart=[];const fa=n=>n.toLocaleString('fa-IR')+' تومان';
function render(){const q=document.getElementById('search').value.trim().toLowerCase();const list=products.filter(p=>(selected==='all'||p.cat===selected)&&(!q||p.name.toLowerCase().includes(q)));document.getElementById('grid').innerHTML=list.map(p=>`<article class="product"><div class="product-img">${p.icon}</div><div class="product-body"><h3>${p.name}</h3><p>${p.desc}</p><span class="price">${fa(p.price)}</span><button class="buy" onclick="addCart(${p.id})">افزودن</button></div></article>`).join('')}
function filter(cat){selected=cat;render();document.getElementById('products').scrollIntoView({behavior:'smooth'})}
function addCart(id){const p=products.find(p=>p.id===id);if(p)cart.push(p);updateCart();openCart()}
function updateCart(){document.getElementById('count').textContent=cart.length.toLocaleString('fa-IR');document.getElementById('items').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><span>${p.name}</span><span>${fa(p.price)} <button class="remove" onclick="removeCart(${i})">حذف</button></span></div>`).join(''):'<p>سبد خرید خالی است.</p>';document.getElementById('total').textContent='جمع: '+fa(cart.reduce((s,p)=>s+p.price,0))}
function removeCart(i){cart.splice(i,1);updateCart()}
function openCart(){document.getElementById('modal').classList.add('show');updateCart()}
function closeCart(e){if(!e||e.target.id==='modal')document.getElementById('modal').classList.remove('show')}
function checkout(){if(!cart.length)return;document.getElementById('cartView').style.display='none';document.getElementById('checkoutView').style.display='block';document.getElementById('cardSuccessView').style.display='none';document.getElementById('successView').style.display='none';document.getElementById('checkoutMsg').textContent='';togglePaymentMethod()}
function showCart(){document.getElementById('checkoutView').style.display='none';document.getElementById('cartView').style.display='block';document.getElementById('checkoutMsg').textContent=''}
function togglePaymentMethod(){const method=document.querySelector('input[name="paymentMethod"]:checked')?.value;document.getElementById('cardTransferBox').style.display=method==='card'?'block':'none';document.getElementById('zarinpalBtn').style.display=method==='zarinpal'?'block':'none';if(method==='card')document.getElementById('cardInfo').textContent='شماره کارت فروشنده: '+CARD_NUMBER}
function customerData(){const name=document.getElementById('customerName').value.trim();const mobile=document.getElementById('customerMobile').value.trim().replace(/\s+/g,'');const email=document.getElementById('customerEmail').value.trim();const msg=document.getElementById('checkoutMsg');if(name.length<2){msg.textContent='لطفاً نام و نام خانوادگی را وارد کن.';return null}if(!/^09\d{9}$/.test(mobile)){msg.textContent='شماره موبایل معتبر وارد کن؛ مثال: 09121234567';return null}if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){msg.textContent='ایمیل واردشده معتبر نیست.';return null}return{name,mobile,email}}
async function startPayment(){const c=customerData();if(!c)return;const msg=document.getElementById('checkoutMsg');msg.textContent='در حال ایجاد سفارش و اتصال به درگاه...';try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY,'Authorization':`Bearer ${API_KEY}`},body:JSON.stringify({action:'create',product_ids:cart.map(p=>p.id),customer_name:c.name,customer_mobile:c.mobile,customer_email:c.email})});const data=await res.json();if(!res.ok||!data.payment_url)throw new Error(data.error||'خطا در ایجاد پرداخت');sessionStorage.setItem('lastOrder',String(data.order_number));window.location.href=data.payment_url}catch(e){msg.textContent=e.message||'خطایی رخ داد. دوباره تلاش کن.'}}
async function submitCardTransfer(){const c=customerData();if(!c)return;const msg=document.getElementById('checkoutMsg');if(CARD_NUMBER.includes('اینجا وارد کنید')){msg.textContent='شماره کارت فروشنده هنوز تنظیم نشده است.';return}msg.textContent='در حال ثبت سفارش...';try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY,'Authorization':`Bearer ${API_KEY}`},body:JSON.stringify({action:'card_transfer',product_ids:cart.map(p=>p.id),customer_name:c.name,customer_mobile:c.mobile,customer_email:c.email})});const data=await res.json();if(!res.ok||!data.order_number)throw new Error(data.error||'ثبت سفارش ناموفق بود.');document.getElementById('checkoutView').style.display='none';document.getElementById('cardSuccessView').style.display='block';document.getElementById('cardSuccessText').textContent=`سفارش شماره ${Number(data.order_number).toLocaleString('fa-IR')} ثبت شد. مبلغ ${fa(data.total_toman)} را کارت‌به‌کارت کن و رسید را برای مدیر فروشگاه ارسال کن.`;sessionStorage.setItem('lastOrder',String(data.order_number));cart=[];updateCart()}catch(e){msg.textContent=e.message||'خطایی رخ داد. دوباره تلاش کن.'}}
async function handlePaymentReturn(){const params=new URLSearchParams(location.search);const result=params.get('payment');const order=params.get('order');const token=params.get('token');if(!result)return;if(result==='success'&&order&&token){document.getElementById('modal').classList.add('show');document.getElementById('cartView').style.display='none';document.getElementById('checkoutView').style.display='none';document.getElementById('cardSuccessView').style.display='none';document.getElementById('successView').style.display='block';document.getElementById('successText').textContent=`سفارش شماره ${Number(order).toLocaleString('fa-IR')} با موفقیت پرداخت شد. لینک‌های دانلود آماده‌اند.`;const box=document.getElementById('downloads');box.innerHTML='<p>در حال آماده‌سازی لینک دانلود...</p>';try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY,'Authorization':`Bearer ${API_KEY}`},body:JSON.stringify({action:'download',order_number:Number(order),token})});const data=await res.json();if(!res.ok)throw new Error(data.error||'دریافت لینک دانلود ناموفق بود.');box.innerHTML=data.links?.length?data.links.map(x=>`<a class="pay" style="display:block;text-decoration:none;text-align:center;margin-top:10px" href="${x.url}" target="_blank" rel="noopener">⬇️ دانلود ${x.name}</a>`).join(''):'<p>فایل محصول هنوز بارگذاری نشده است.</p>';cart=[];updateCart()}catch(e){box.innerHTML=`<p class="checkout-msg">${e.message}</p>`}}else if(result==='cancelled'){alert(`پرداخت سفارش ${order||''} لغو شد.`)}else if(result==='failed'){alert('پرداخت ناموفق بود. لطفاً دوباره تلاش کن.')}history.replaceState({},document.title,location.pathname)}
render();updateCart();handlePaymentReturn();